// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/demo.proto

package com.cnc.dubbo.proto;

public final class DemoServiceProto {
  private DemoServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_service_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_service_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_service_HelloReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_service_HelloReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024resources/demo.proto\022\014demo_service\"\034\n\014" +
      "HelloRequest\022\014\n\004name\030\001 \001(\t\"\035\n\nHelloReply" +
      "\022\017\n\007message\030\001 \001(\t2Q\n\013DemoService\022B\n\010SayH" +
      "ello\022\032.demo_service.HelloRequest\032\030.demo_" +
      "service.HelloReply\"\000B7\n\023com.cnc.dubbo.pr" +
      "otoB\020DemoServiceProtoP\001\242\002\013DemoServiceb\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData, new com.google.protobuf.Descriptors.FileDescriptor[]{});
    internal_static_demo_service_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_demo_service_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_service_HelloRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_demo_service_HelloReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_demo_service_HelloReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_service_HelloReply_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
