// Generated by the proto buffer compiler.  DO NOT EDIT!
// source: resources/demo.proto

package com.cnc.dubbo.proto;

public interface HelloReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:demo_service.HelloReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
