swagger:
  enabled: true

server:
  port: 8099
  application:
    name: eebo.ehr.attendance3_calc
  servlet:
    encoding:
      charset: utf-8
      enabled: true

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      one:
        url: jdbc:mysql://attm-mysql-dev.2haohr.com:3306/ehr-attendance?serverTimezone=Asia/Shanghai&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&rewriteBatchedStatements=true
        username: root
        password: Z2OrHKcVkS
      two:
        url: jdbc:mysql://attm-mysql-dev.2haohr.com:3306/ehr-attendance?serverTimezone=Asia/Shanghai&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&rewriteBatchedStatements=true
        username: root
        password: Z2OrHKcVkS
      # 初始化连接大小
      initial-size: 10
      # 最小空闲连接数
      min-idle: 10
      max-active: 20
      max-wait: 6000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中的最小生存时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 配置监控统计拦截的filters
      filters: stat
  rabbitmq:
    host: rabbitmq-dev.2haohr.com
    port: 5672
    username: guest
    password: guest
    publisher-returns: true
    publisher-confirms: true
    template:
      mandatory: true

fastdep:
  redis:
    #数据库索引
    redis1: # 考勤专用实例 0 库
      database: 0
      host: 106.75.132.134
      port: 6379
      password: 123456
      lettuce:
        pool:
          min-idle: 6
          max-idle: 10
          max-active: 20
          max-wait: 100
    redis2: # 公共实例 0 库
      database: 0
      host: redis-dev.2haohr.com
      port: 6379
      password: 123456
      lettuce:
        pool:
          min-idle: 6
          max-idle: 10
          max-active: 20
          max-wait: 100
    redis3:  # 公共实例 2 库
      database: 2
      host: redis-dev.2haohr.com
      port: 6379
      password: 123456
      lettuce:
        pool:
          min-idle: 6
          max-idle: 10
          max-active: 20
          max-wait: 100

#canal dev环境
canal:
  #server: 106.75.169.10:11111
  server:
  #zkServer: 106.75.168.229:2181
  #zkServer: 10.13.132.122:2181,10.13.100.201:2181,10.13.39.80:2181
  zkServer: 10.211.5.10:2181
  destination: ehr-attendance-dev
  db:
    userName: canal
    password: canal

attendance:
  thread-pool:
    schedule:
      core: 8
      max: 16
      capacity: 500
    execute:
      core: 12
      max: 24
      capacity: 500
    select:
      core: 20
      max: 40
      capacity: 500
    store:
      core: 20
      max: 40
      capacity: 500
  calculate:
    batch-size: 35
  calcResultCompareUrl: http://intranet-dev.2haohr.com/compare_server/compare/run
  intranetUrl: http://intranet-dev.2haohr.com/ucenter/
  calc:
    card:
      queue:
        name: eebo.ehr.attendance3_calc.card
        concurrency: 12
      exchange:
        name: eebo.ehr.attendance3_calc
      routing:
        key: eebo.ehr.attendance3_calc.card
    month:
      queue:
        name: eebo.ehr.attendance3_calc.month
        concurrency: 1
      exchange:
        name: eebo.ehr.attendance3_calc
      routing:
        key: eebo.ehr.attendance3_calc.month
  leave:
    overtime-vacation:
      queue:
        name: eebo.ehr.leave_management.accounting.handle_overtimes_submit
      exchange:
        name: eebo.ehr.leave_management
      routing:
        key: eebo.ehr.leave_management.accounting.handle_overtimes_submit


logging:
  config: classpath:logback-elk.xml
  elk:
    destination: elk6.dev.com:9601
  level:
    root: INFO

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
#  configuration:
#     log-impl: org.apache.ibatis.logging.stdout.StdOutImpl