// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package org.cnc.protobuf.protos;

public final class UserProto {
  private UserProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.wxw.notes.protobuf.proto.User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *自身属性
     * </pre>
     *
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>string code = 2;</code>
     */
    java.lang.String getCode();
    /**
     * <code>string code = 2;</code>
     */
    com.google.protobuf.ByteString
        getCodeBytes();

    /**
     * <code>string name = 3;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 3;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     * 对象
     * </pre>
     *
     * <code>.com.wxw.notes.protobuf.proto.NickName nickName = 4;</code>
     */
    boolean hasNickName();
    /**
     * <pre>
     * 对象
     * </pre>
     *
     * <code>.com.wxw.notes.protobuf.proto.NickName nickName = 4;</code>
     */
    org.cnc.protobuf.protos.UserProto.NickName getNickName();
    /**
     * <pre>
     * 对象
     * </pre>
     *
     * <code>.com.wxw.notes.protobuf.proto.NickName nickName = 4;</code>
     */
    org.cnc.protobuf.protos.UserProto.NickNameOrBuilder getNickNameOrBuilder();

    /**
     * <pre>
     *list 引用类型
     * </pre>
     *
     * <code>repeated string strList = 5;</code>
     */
    java.util.List<java.lang.String>
        getStrListList();
    /**
     * <pre>
     *list 引用类型
     * </pre>
     *
     * <code>repeated string strList = 5;</code>
     */
    int getStrListCount();
    /**
     * <pre>
     *list 引用类型
     * </pre>
     *
     * <code>repeated string strList = 5;</code>
     */
    java.lang.String getStrList(int index);
    /**
     * <pre>
     *list 引用类型
     * </pre>
     *
     * <code>repeated string strList = 5;</code>
     */
    com.google.protobuf.ByteString
        getStrListBytes(int index);
  }
  /**
   * <pre>
   *创建一个 User 对象
   * </pre>
   *
   * Protobuf type {@code com.wxw.notes.protobuf.proto.User}
   */
  public  static final class User extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.wxw.notes.protobuf.proto.User)
      UserOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private User() {
      id_ = 0;
      code_ = "";
      name_ = "";
      strList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              code_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 34: {
              org.cnc.protobuf.protos.UserProto.NickName.Builder subBuilder = null;
              if (nickName_ != null) {
                subBuilder = nickName_.toBuilder();
              }
              nickName_ = input.readMessage(org.cnc.protobuf.protos.UserProto.NickName.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(nickName_);
                nickName_ = subBuilder.buildPartial();
              }

              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                strList_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              strList_.add(s);
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          strList_ = strList_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.cnc.protobuf.protos.UserProto.internal_static_com_wxw_notes_protobuf_proto_User_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.cnc.protobuf.protos.UserProto.internal_static_com_wxw_notes_protobuf_proto_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.cnc.protobuf.protos.UserProto.User.class, org.cnc.protobuf.protos.UserProto.User.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <pre>
     *自身属性
     * </pre>
     *
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int CODE_FIELD_NUMBER = 2;
    private volatile java.lang.Object code_;
    /**
     * <code>string code = 2;</code>
     */
    public java.lang.String getCode() {
      java.lang.Object ref = code_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        code_ = s;
        return s;
      }
    }
    /**
     * <code>string code = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCodeBytes() {
      java.lang.Object ref = code_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 3;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NICKNAME_FIELD_NUMBER = 4;
    private org.cnc.protobuf.protos.UserProto.NickName nickName_;
    /**
     * <pre>
     * 对象
     * </pre>
     *
     * <code>.com.wxw.notes.protobuf.proto.NickName nickName = 4;</code>
     */
    public boolean hasNickName() {
      return nickName_ != null;
    }
    /**
     * <pre>
     * 对象
     * </pre>
     *
     * <code>.com.wxw.notes.protobuf.proto.NickName nickName = 4;</code>
     */
    public org.cnc.protobuf.protos.UserProto.NickName getNickName() {
      return nickName_ == null ? org.cnc.protobuf.protos.UserProto.NickName.getDefaultInstance() : nickName_;
    }
    /**
     * <pre>
     * 对象
     * </pre>
     *
     * <code>.com.wxw.notes.protobuf.proto.NickName nickName = 4;</code>
     */
    public org.cnc.protobuf.protos.UserProto.NickNameOrBuilder getNickNameOrBuilder() {
      return getNickName();
    }

    public static final int STRLIST_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList strList_;
    /**
     * <pre>
     *list 引用类型
     * </pre>
     *
     * <code>repeated string strList = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getStrListList() {
      return strList_;
    }
    /**
     * <pre>
     *list 引用类型
     * </pre>
     *
     * <code>repeated string strList = 5;</code>
     */
    public int getStrListCount() {
      return strList_.size();
    }
    /**
     * <pre>
     *list 引用类型
     * </pre>
     *
     * <code>repeated string strList = 5;</code>
     */
    public java.lang.String getStrList(int index) {
      return strList_.get(index);
    }
    /**
     * <pre>
     *list 引用类型
     * </pre>
     *
     * <code>repeated string strList = 5;</code>
     */
    public com.google.protobuf.ByteString
        getStrListBytes(int index) {
      return strList_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, code_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
      }
      if (nickName_ != null) {
        output.writeMessage(4, getNickName());
      }
      for (int i = 0; i < strList_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, strList_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, code_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
      }
      if (nickName_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getNickName());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < strList_.size(); i++) {
          dataSize += computeStringSizeNoTag(strList_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getStrListList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.cnc.protobuf.protos.UserProto.User)) {
        return super.equals(obj);
      }
      org.cnc.protobuf.protos.UserProto.User other = (org.cnc.protobuf.protos.UserProto.User) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getCode()
          .equals(other.getCode());
      result = result && getName()
          .equals(other.getName());
      result = result && (hasNickName() == other.hasNickName());
      if (hasNickName()) {
        result = result && getNickName()
            .equals(other.getNickName());
      }
      result = result && getStrListList()
          .equals(other.getStrListList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (hasNickName()) {
        hash = (37 * hash) + NICKNAME_FIELD_NUMBER;
        hash = (53 * hash) + getNickName().hashCode();
      }
      if (getStrListCount() > 0) {
        hash = (37 * hash) + STRLIST_FIELD_NUMBER;
        hash = (53 * hash) + getStrListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.cnc.protobuf.protos.UserProto.User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cnc.protobuf.protos.UserProto.User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cnc.protobuf.protos.UserProto.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cnc.protobuf.protos.UserProto.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cnc.protobuf.protos.UserProto.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cnc.protobuf.protos.UserProto.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cnc.protobuf.protos.UserProto.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.cnc.protobuf.protos.UserProto.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.cnc.protobuf.protos.UserProto.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.cnc.protobuf.protos.UserProto.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.cnc.protobuf.protos.UserProto.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.cnc.protobuf.protos.UserProto.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.cnc.protobuf.protos.UserProto.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *创建一个 User 对象
     * </pre>
     *
     * Protobuf type {@code com.wxw.notes.protobuf.proto.User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.wxw.notes.protobuf.proto.User)
        org.cnc.protobuf.protos.UserProto.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.cnc.protobuf.protos.UserProto.internal_static_com_wxw_notes_protobuf_proto_User_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.cnc.protobuf.protos.UserProto.internal_static_com_wxw_notes_protobuf_proto_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.cnc.protobuf.protos.UserProto.User.class, org.cnc.protobuf.protos.UserProto.User.Builder.class);
      }

      // Construct using org.cnc.protobuf.protos.UserProto.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        code_ = "";

        name_ = "";

        if (nickNameBuilder_ == null) {
          nickName_ = null;
        } else {
          nickName_ = null;
          nickNameBuilder_ = null;
        }
        strList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.cnc.protobuf.protos.UserProto.internal_static_com_wxw_notes_protobuf_proto_User_descriptor;
      }

      @java.lang.Override
      public org.cnc.protobuf.protos.UserProto.User getDefaultInstanceForType() {
        return org.cnc.protobuf.protos.UserProto.User.getDefaultInstance();
      }

      @java.lang.Override
      public org.cnc.protobuf.protos.UserProto.User build() {
        org.cnc.protobuf.protos.UserProto.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.cnc.protobuf.protos.UserProto.User buildPartial() {
        org.cnc.protobuf.protos.UserProto.User result = new org.cnc.protobuf.protos.UserProto.User(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.code_ = code_;
        result.name_ = name_;
        if (nickNameBuilder_ == null) {
          result.nickName_ = nickName_;
        } else {
          result.nickName_ = nickNameBuilder_.build();
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          strList_ = strList_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.strList_ = strList_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.cnc.protobuf.protos.UserProto.User) {
          return mergeFrom((org.cnc.protobuf.protos.UserProto.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.cnc.protobuf.protos.UserProto.User other) {
        if (other == org.cnc.protobuf.protos.UserProto.User.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getCode().isEmpty()) {
          code_ = other.code_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.hasNickName()) {
          mergeNickName(other.getNickName());
        }
        if (!other.strList_.isEmpty()) {
          if (strList_.isEmpty()) {
            strList_ = other.strList_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureStrListIsMutable();
            strList_.addAll(other.strList_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.cnc.protobuf.protos.UserProto.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.cnc.protobuf.protos.UserProto.User) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <pre>
       *自身属性
       * </pre>
       *
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <pre>
       *自身属性
       * </pre>
       *
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *自身属性
       * </pre>
       *
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object code_ = "";
      /**
       * <code>string code = 2;</code>
       */
      public java.lang.String getCode() {
        java.lang.Object ref = code_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          code_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string code = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCodeBytes() {
        java.lang.Object ref = code_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          code_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string code = 2;</code>
       */
      public Builder setCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string code = 2;</code>
       */
      public Builder clearCode() {
        
        code_ = getDefaultInstance().getCode();
        onChanged();
        return this;
      }
      /**
       * <code>string code = 2;</code>
       */
      public Builder setCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        code_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 3;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private org.cnc.protobuf.protos.UserProto.NickName nickName_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.cnc.protobuf.protos.UserProto.NickName, org.cnc.protobuf.protos.UserProto.NickName.Builder, org.cnc.protobuf.protos.UserProto.NickNameOrBuilder> nickNameBuilder_;
      /**
       * <pre>
       * 对象
       * </pre>
       *
       * <code>.com.wxw.notes.protobuf.proto.NickName nickName = 4;</code>
       */
      public boolean hasNickName() {
        return nickNameBuilder_ != null || nickName_ != null;
      }
      /**
       * <pre>
       * 对象
       * </pre>
       *
       * <code>.com.wxw.notes.protobuf.proto.NickName nickName = 4;</code>
       */
      public org.cnc.protobuf.protos.UserProto.NickName getNickName() {
        if (nickNameBuilder_ == null) {
          return nickName_ == null ? org.cnc.protobuf.protos.UserProto.NickName.getDefaultInstance() : nickName_;
        } else {
          return nickNameBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 对象
       * </pre>
       *
       * <code>.com.wxw.notes.protobuf.proto.NickName nickName = 4;</code>
       */
      public Builder setNickName(org.cnc.protobuf.protos.UserProto.NickName value) {
        if (nickNameBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          nickName_ = value;
          onChanged();
        } else {
          nickNameBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * 对象
       * </pre>
       *
       * <code>.com.wxw.notes.protobuf.proto.NickName nickName = 4;</code>
       */
      public Builder setNickName(
          org.cnc.protobuf.protos.UserProto.NickName.Builder builderForValue) {
        if (nickNameBuilder_ == null) {
          nickName_ = builderForValue.build();
          onChanged();
        } else {
          nickNameBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * 对象
       * </pre>
       *
       * <code>.com.wxw.notes.protobuf.proto.NickName nickName = 4;</code>
       */
      public Builder mergeNickName(org.cnc.protobuf.protos.UserProto.NickName value) {
        if (nickNameBuilder_ == null) {
          if (nickName_ != null) {
            nickName_ =
              org.cnc.protobuf.protos.UserProto.NickName.newBuilder(nickName_).mergeFrom(value).buildPartial();
          } else {
            nickName_ = value;
          }
          onChanged();
        } else {
          nickNameBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * 对象
       * </pre>
       *
       * <code>.com.wxw.notes.protobuf.proto.NickName nickName = 4;</code>
       */
      public Builder clearNickName() {
        if (nickNameBuilder_ == null) {
          nickName_ = null;
          onChanged();
        } else {
          nickName_ = null;
          nickNameBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * 对象
       * </pre>
       *
       * <code>.com.wxw.notes.protobuf.proto.NickName nickName = 4;</code>
       */
      public org.cnc.protobuf.protos.UserProto.NickName.Builder getNickNameBuilder() {
        
        onChanged();
        return getNickNameFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 对象
       * </pre>
       *
       * <code>.com.wxw.notes.protobuf.proto.NickName nickName = 4;</code>
       */
      public org.cnc.protobuf.protos.UserProto.NickNameOrBuilder getNickNameOrBuilder() {
        if (nickNameBuilder_ != null) {
          return nickNameBuilder_.getMessageOrBuilder();
        } else {
          return nickName_ == null ?
              org.cnc.protobuf.protos.UserProto.NickName.getDefaultInstance() : nickName_;
        }
      }
      /**
       * <pre>
       * 对象
       * </pre>
       *
       * <code>.com.wxw.notes.protobuf.proto.NickName nickName = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.cnc.protobuf.protos.UserProto.NickName, org.cnc.protobuf.protos.UserProto.NickName.Builder, org.cnc.protobuf.protos.UserProto.NickNameOrBuilder> 
          getNickNameFieldBuilder() {
        if (nickNameBuilder_ == null) {
          nickNameBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.cnc.protobuf.protos.UserProto.NickName, org.cnc.protobuf.protos.UserProto.NickName.Builder, org.cnc.protobuf.protos.UserProto.NickNameOrBuilder>(
                  getNickName(),
                  getParentForChildren(),
                  isClean());
          nickName_ = null;
        }
        return nickNameBuilder_;
      }

      private com.google.protobuf.LazyStringList strList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureStrListIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          strList_ = new com.google.protobuf.LazyStringArrayList(strList_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <pre>
       *list 引用类型
       * </pre>
       *
       * <code>repeated string strList = 5;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getStrListList() {
        return strList_.getUnmodifiableView();
      }
      /**
       * <pre>
       *list 引用类型
       * </pre>
       *
       * <code>repeated string strList = 5;</code>
       */
      public int getStrListCount() {
        return strList_.size();
      }
      /**
       * <pre>
       *list 引用类型
       * </pre>
       *
       * <code>repeated string strList = 5;</code>
       */
      public java.lang.String getStrList(int index) {
        return strList_.get(index);
      }
      /**
       * <pre>
       *list 引用类型
       * </pre>
       *
       * <code>repeated string strList = 5;</code>
       */
      public com.google.protobuf.ByteString
          getStrListBytes(int index) {
        return strList_.getByteString(index);
      }
      /**
       * <pre>
       *list 引用类型
       * </pre>
       *
       * <code>repeated string strList = 5;</code>
       */
      public Builder setStrList(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStrListIsMutable();
        strList_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *list 引用类型
       * </pre>
       *
       * <code>repeated string strList = 5;</code>
       */
      public Builder addStrList(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStrListIsMutable();
        strList_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *list 引用类型
       * </pre>
       *
       * <code>repeated string strList = 5;</code>
       */
      public Builder addAllStrList(
          java.lang.Iterable<java.lang.String> values) {
        ensureStrListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, strList_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *list 引用类型
       * </pre>
       *
       * <code>repeated string strList = 5;</code>
       */
      public Builder clearStrList() {
        strList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *list 引用类型
       * </pre>
       *
       * <code>repeated string strList = 5;</code>
       */
      public Builder addStrListBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureStrListIsMutable();
        strList_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.wxw.notes.protobuf.proto.User)
    }

    // @@protoc_insertion_point(class_scope:com.wxw.notes.protobuf.proto.User)
    private static final org.cnc.protobuf.protos.UserProto.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.cnc.protobuf.protos.UserProto.User();
    }

    public static org.cnc.protobuf.protos.UserProto.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      @java.lang.Override
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new User(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.cnc.protobuf.protos.UserProto.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NickNameOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.wxw.notes.protobuf.proto.NickName)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string nickName = 1;</code>
     */
    java.lang.String getNickName();
    /**
     * <code>string nickName = 1;</code>
     */
    com.google.protobuf.ByteString
        getNickNameBytes();
  }
  /**
   * <pre>
   * 定义一个新的Name对象
   * </pre>
   *
   * Protobuf type {@code com.wxw.notes.protobuf.proto.NickName}
   */
  public  static final class NickName extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.wxw.notes.protobuf.proto.NickName)
      NickNameOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NickName.newBuilder() to construct.
    private NickName(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NickName() {
      nickName_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NickName(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              nickName_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.cnc.protobuf.protos.UserProto.internal_static_com_wxw_notes_protobuf_proto_NickName_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.cnc.protobuf.protos.UserProto.internal_static_com_wxw_notes_protobuf_proto_NickName_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.cnc.protobuf.protos.UserProto.NickName.class, org.cnc.protobuf.protos.UserProto.NickName.Builder.class);
    }

    public static final int NICKNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object nickName_;
    /**
     * <code>string nickName = 1;</code>
     */
    public java.lang.String getNickName() {
      java.lang.Object ref = nickName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nickName_ = s;
        return s;
      }
    }
    /**
     * <code>string nickName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNickNameBytes() {
      java.lang.Object ref = nickName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nickName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNickNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nickName_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNickNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nickName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.cnc.protobuf.protos.UserProto.NickName)) {
        return super.equals(obj);
      }
      org.cnc.protobuf.protos.UserProto.NickName other = (org.cnc.protobuf.protos.UserProto.NickName) obj;

      boolean result = true;
      result = result && getNickName()
          .equals(other.getNickName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NICKNAME_FIELD_NUMBER;
      hash = (53 * hash) + getNickName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.cnc.protobuf.protos.UserProto.NickName parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cnc.protobuf.protos.UserProto.NickName parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cnc.protobuf.protos.UserProto.NickName parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cnc.protobuf.protos.UserProto.NickName parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cnc.protobuf.protos.UserProto.NickName parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cnc.protobuf.protos.UserProto.NickName parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cnc.protobuf.protos.UserProto.NickName parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.cnc.protobuf.protos.UserProto.NickName parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.cnc.protobuf.protos.UserProto.NickName parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.cnc.protobuf.protos.UserProto.NickName parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.cnc.protobuf.protos.UserProto.NickName parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.cnc.protobuf.protos.UserProto.NickName parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.cnc.protobuf.protos.UserProto.NickName prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 定义一个新的Name对象
     * </pre>
     *
     * Protobuf type {@code com.wxw.notes.protobuf.proto.NickName}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.wxw.notes.protobuf.proto.NickName)
        org.cnc.protobuf.protos.UserProto.NickNameOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.cnc.protobuf.protos.UserProto.internal_static_com_wxw_notes_protobuf_proto_NickName_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.cnc.protobuf.protos.UserProto.internal_static_com_wxw_notes_protobuf_proto_NickName_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.cnc.protobuf.protos.UserProto.NickName.class, org.cnc.protobuf.protos.UserProto.NickName.Builder.class);
      }

      // Construct using org.cnc.protobuf.protos.UserProto.NickName.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        nickName_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.cnc.protobuf.protos.UserProto.internal_static_com_wxw_notes_protobuf_proto_NickName_descriptor;
      }

      @java.lang.Override
      public org.cnc.protobuf.protos.UserProto.NickName getDefaultInstanceForType() {
        return org.cnc.protobuf.protos.UserProto.NickName.getDefaultInstance();
      }

      @java.lang.Override
      public org.cnc.protobuf.protos.UserProto.NickName build() {
        org.cnc.protobuf.protos.UserProto.NickName result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.cnc.protobuf.protos.UserProto.NickName buildPartial() {
        org.cnc.protobuf.protos.UserProto.NickName result = new org.cnc.protobuf.protos.UserProto.NickName(this);
        result.nickName_ = nickName_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.cnc.protobuf.protos.UserProto.NickName) {
          return mergeFrom((org.cnc.protobuf.protos.UserProto.NickName)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.cnc.protobuf.protos.UserProto.NickName other) {
        if (other == org.cnc.protobuf.protos.UserProto.NickName.getDefaultInstance()) return this;
        if (!other.getNickName().isEmpty()) {
          nickName_ = other.nickName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.cnc.protobuf.protos.UserProto.NickName parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.cnc.protobuf.protos.UserProto.NickName) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object nickName_ = "";
      /**
       * <code>string nickName = 1;</code>
       */
      public java.lang.String getNickName() {
        java.lang.Object ref = nickName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nickName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nickName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNickNameBytes() {
        java.lang.Object ref = nickName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nickName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nickName = 1;</code>
       */
      public Builder setNickName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nickName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nickName = 1;</code>
       */
      public Builder clearNickName() {
        
        nickName_ = getDefaultInstance().getNickName();
        onChanged();
        return this;
      }
      /**
       * <code>string nickName = 1;</code>
       */
      public Builder setNickNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nickName_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.wxw.notes.protobuf.proto.NickName)
    }

    // @@protoc_insertion_point(class_scope:com.wxw.notes.protobuf.proto.NickName)
    private static final org.cnc.protobuf.protos.UserProto.NickName DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.cnc.protobuf.protos.UserProto.NickName();
    }

    public static org.cnc.protobuf.protos.UserProto.NickName getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NickName>
        PARSER = new com.google.protobuf.AbstractParser<NickName>() {
      @java.lang.Override
      public NickName parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NickName(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NickName> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NickName> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.cnc.protobuf.protos.UserProto.NickName getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wxw_notes_protobuf_proto_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wxw_notes_protobuf_proto_User_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wxw_notes_protobuf_proto_NickName_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wxw_notes_protobuf_proto_NickName_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nUser.proto\022\034com.wxw.notes.protobuf.pro" +
      "to\"y\n\004User\022\n\n\002id\030\001 \001(\005\022\014\n\004code\030\002 \001(\t\022\014\n\004" +
      "name\030\003 \001(\t\0228\n\010nickName\030\004 \001(\0132&.com.wxw.n" +
      "otes.protobuf.proto.NickName\022\017\n\007strList\030" +
      "\005 \003(\t\"\034\n\010NickName\022\020\n\010nickName\030\001 \001(\tB$\n\027o" +
      "rg.cnc.protobuf.protosB\tUserProtob\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_wxw_notes_protobuf_proto_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_wxw_notes_protobuf_proto_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wxw_notes_protobuf_proto_User_descriptor,
        new java.lang.String[] { "Id", "Code", "Name", "NickName", "StrList", });
    internal_static_com_wxw_notes_protobuf_proto_NickName_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_wxw_notes_protobuf_proto_NickName_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wxw_notes_protobuf_proto_NickName_descriptor,
        new java.lang.String[] { "NickName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
