app:
  name: example
  version: 0.1.1
  author: tony


spring:
  datasource:
    druid:
      username: root
      password: admin123
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://114.67.81.63:3307/java_std?serverTimezone=UTC
      type: com.alibaba.druid.pool.DruidDataSource
      #   数据源其他配置
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  rabbitmq:
    host: 114.67.81.63
    port: 5680
    username: guest
    password: guest


logging:
  level:
    org.framework: info
  config: classpath:logback-spring.xml

custom:
  mq:
    rabbitmq:
      exchanges:
        myexchange:
          name: "com.cnc.rabbit.exchange.my-exchange"
          queues:
            myqueue1:
              name: "com.cnc.rabbit.queue.my-queue1"
              binding-key: "com.cnc.rabbit.binding.my-queue1-to-my-exchange"
              auto-delete: false
              durable: true
            myqueue2:
              name: "com.cnc.rabbit.queue.my-queue2"
              binding-key: "com.cnc.rabbit.binding.my-queue2-to-my-exchange"
              auto-delete: false
              durable: true
      ot-convert:
        queue: com.cnc.rabbit.queue.my-queue1
        exchange: com.cnc.rabbit.exchange.my-exchange1
        # 以下可选的消息 参数
      month-attendance:
        queue: com.cnc.rabbit.queue.my-queue2
        exchange: com.cnc.rabbit.exchange.my-exchange1
        # 以下可选的消息 参数

